version: "3.6"

networks:
  grafnet:
    external: true

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom-data:/prometheus
    networks:
      - promnet
volumes:
  prom-data:
    name: prom-data
    external: false