global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: ida-grafana-prometheus
    scrape_interval: 15s 
    static_configs:
      - targets: ["192.168.10.64:9090"]
  - job_name: ida-grafana-node_exporter  
    scrape_interval: 15s 
    static_configs:
      - targets: ["192.168.10.64:9100"]